name: App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test

      - name: Report Test Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v1

      - name: Generate Coverage Badges
        if: always()
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
          no-commit: true
          output-folder: ./badges

      - name: Lint Project
        run: yarn lint

      - name: Archive Code Coverage Results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./coverage

      - name: Archive Coverage Badges
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./badges
