name: App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test

      - name: Report Test Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v1

      - name: Generate Coverage Badges
        if: always()
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
          no-commit: true
          output-folder: ./badges

      - name: Lint Project
        run: yarn lint

      - name: Archive Code Coverage Results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./coverage

      - name: Archive Coverage Badges
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-badges
          path: ./badges

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Compile Typescript and Build
        run: yarn build

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: app-dist
          path: ./dist

  create-release-notes:
    name: Create Release Notes
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download App Dist
        uses: actions/download-artifact@v3
        with:
          name: app-dist
          path: dist

      - name: Download Code Coverage Report
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: coverage

      - name: Download Coverage Badges
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-badges
          path: badges

      - name: Generate Semantic Version and Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          git-message: "chore(release): {version}"
          release-count: 0
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Create Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist, coverage"
          tag: ${{ steps.changelog.outputs.tag }}
          makeLatest: true
          body: ${{ steps.changelog.outputs.clean_changelog }}

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: create-release-notes
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download App Dist
        uses: actions/download-artifact@v3
        with:
          name: app-dist
          path: dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
