name: Pull Request CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    name: Test, Lint, Build, and Report Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Run Lint
        run: yarn lint

      - name: Compile Typescript and Build
        run: yarn build

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v1
